### PR TITLE
Fix: workflow's build remove useless calls and add new uploads

### PR DESCRIPTION
**Pull request by 8MiYile**
I like your Mod.
You will like your workflow better after I change it

### CODE REVIEW

**Comment by mrmelon54** [comment]
How will I like my workflow better with those changes?
I have no need for uploading an artifact as the "DEPLOY" stage uploads it to storage on my server anyway.

**Comment by 8MiYile** [comment]
@MrMelon54 
Sometimes I'm more used to looking at Artifact builds that
So what kind of process do you want

I can't access your website from China

**Comment by mrmelon54** [comment]
My process ends with uploading builds to Modrinth, that's where I would recommend going for published builds.

**Comment by 8MiYile** [comment]
@MrMelon54 
First agree to this Pull Request
Then add this call
https://github.com/RubixDev/modrinth-upload
Isn't that better?

**Comment by kckarnige** [comment]
💀

**Pull request closed without merging**
